# Generated by Django 4.2.11 on 2024-09-05 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_variantread_genomeurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantCallProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('referenceGenomeURL', models.URLField(blank=True, default=None, max_length=256, null=True)),
                ('genomeURL', models.URLField(blank=True, default=None, max_length=256, null=True)),
                ('vcfURL', models.URLField(blank=True, default=None, max_length=256, null=True)),
                ('folder', projects.models.DirectoryPathField(blank=True, default=None, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedVariantCallProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models.fileDirectoryCalls)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.variantcallproject')),
            ],
        ),
    ]
