# Generated by Django 4.2.11 on 2024-09-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_variantcallproject_uploadedvariantcallprojectfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantcallproject',
            name='folder',
        ),
    ]
