# Generated by Django 4.2.11 on 2024-09-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_variantcallproject_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantcallproject',
            name='folder',
            field=models.CharField(default='', editable=False, max_length=256),
        ),
    ]
