# Generated by Django 4.2.11 on 2024-10-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_variantcallproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantcallproject',
            name='log',
            field=models.URLField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
